apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - infrastructure/helmrepositories.yaml
  - infrastructure/cloudnative-pg
  - infrastructure/prometheus-operator
  - infrastructure/cert-manager
  - infrastructure/volsync
  - infrastructure/metallb
  - apps/sonarr
