apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: volsync
  namespace: volsync
spec:
  chart:
    spec:
      chart: volsync
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values: {}
